:- multifile move/1.

move('Hidden Power Bug').
move('Hidden Power Dark').
move('Hidden Power Dragon').
move('Hidden Power Electric').
move('Hidden Power Fighting').
move('Hidden Power Fire').
move('Hidden Power Flying').
move('Hidden Power Ghost').
move('Hidden Power Grass').
move('Hidden Power Ground').
move('Hidden Power Ice').
move('Hidden Power Poison').
move('Hidden Power Psychic').
move('Hidden Power Rock').
move('Hidden Power Steel').
move('Hidden Power Water').
move('Hidden Power [Bug]').
move('Hidden Power [Dark]').
move('Hidden Power [Dragon]').
move('Hidden Power [Electric]').
move('Hidden Power [Fighting]').
move('Hidden Power [Fire]').
move('Hidden Power [Flying]').
move('Hidden Power [Ghost]').
move('Hidden Power [Grass]').
move('Hidden Power [Ground]').
move('Hidden Power [Ice]').
move('Hidden Power [Poison]').
move('Hidden Power [Psychic]').
move('Hidden Power [Rock]').
move('Hidden Power [Steel]').
move('Hidden Power [Water]').

hidden_power('Hidden Power Bug').
hidden_power('Hidden Power Dark').
hidden_power('Hidden Power Dragon').
hidden_power('Hidden Power Electric').
hidden_power('Hidden Power Fighting').
hidden_power('Hidden Power Fire').
hidden_power('Hidden Power Flying').
hidden_power('Hidden Power Ghost').
hidden_power('Hidden Power Grass').
hidden_power('Hidden Power Ground').
hidden_power('Hidden Power Ice').
hidden_power('Hidden Power Poison').
hidden_power('Hidden Power Psychic').
hidden_power('Hidden Power Rock').
hidden_power('Hidden Power Steel').
hidden_power('Hidden Power Water').
hidden_power('Hidden Power [Bug]').
hidden_power('Hidden Power [Dark]').
hidden_power('Hidden Power [Dragon]').
hidden_power('Hidden Power [Electric]').
hidden_power('Hidden Power [Fighting]').
hidden_power('Hidden Power [Fire]').
hidden_power('Hidden Power [Flying]').
hidden_power('Hidden Power [Ghost]').
hidden_power('Hidden Power [Grass]').
hidden_power('Hidden Power [Ground]').
hidden_power('Hidden Power [Ice]').
hidden_power('Hidden Power [Poison]').
hidden_power('Hidden Power [Psychic]').
hidden_power('Hidden Power [Rock]').
hidden_power('Hidden Power [Steel]').
hidden_power('Hidden Power [Water]').